title = "FACODI — Faculdade Comunitária Digital"
baseurl = "https://facodi.pt/"
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableRobotsTXT = true
languageCode = "pt-PT"
rssLimit = 10
summarylength = 30

defaultContentLanguage = "pt"
# English configuration is kept in languages.toml but disabled by default.
disableLanguages = ["en"]
defaultContentLanguageInSubdir = false

copyRight = "2024 FACODI — Faculdade Comunitária Digital"

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS", "searchIndex"]
  section = ["HTML", "RSS", "SITEMAP"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[outputFormats.SITEMAP]
  mediaType = "application/xml"
  baseName = "sitemap"
  isHTML = false
  isPlainText = true
  noUgly = true
  rel = "sitemap"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.7

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "30m"

[taxonomies]
  tag = "tags"
  topic = "topics"

[permalinks]
  blog = "/blog/:slug/"
  docs = "/docs/:sections[1:]/:slug/"
  courses = "/courses/:sections[1:]/"

[minify.tdewolff.html]
  keepWhitespace = false

[pagination]
  pagerSize = 10

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
      name = "tags"
      weight = 80
    [[related.indices]]
      name = "date"
      weight = 10
