[pt]
  languageName = "PortuguÃªs"
  weight = 10
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Desenvolvido por <a class="text-muted" href="https://monynha.com/" target="_blank" rel="noopener">Monynha Softwares</a>'
    alertText = ''
