[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'FACODI — Faculdade Comunitária Digital'
    [pt.params.facodi]
      languageLabel = "Português"

[en]
  languageName = "English"
  contentDir = "content"
  weight = 2
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'FACODI — Digital Community College'
    [en.params.facodi]
      languageLabel = "English"

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 3
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = 'FACODI — Faculté Communautaire Numérique'
    [fr.params.facodi]
      languageLabel = "Français"

[es]
  languageName = "Español"
  contentDir = "content"
  weight = 4
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
    footer = 'FACODI — Facultad Comunitaria Digital'
    [es.params.facodi]
      languageLabel = "Español"
