[pt]
  languageName = "PortuguÃªs"
  contentDir = "content"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Mantido com carinho pela <a class="text-muted" href="https://monynha.com/" target="_blank" rel="noopener">Monynha Softwares</a>.'
    alertText = ''

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 2
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Crafted by the <a class="text-muted" href="https://monynha.com/" target="_blank" rel="noopener">Monynha Softwares</a> community.'
    alertText = ''
