[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 10
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Construído pela comunidade <a class="text-muted" href="https://github.com/Monynha-Softwares/facodi.pt">FACODI</a>'

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 20
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    titleAddition = "Community Digital College"
    footer = 'Built with ❤️ by the <a class="text-muted" href="https://github.com/Monynha-Softwares/facodi.pt">FACODI community</a>'
