[pt]
  languageName = "Português"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Criado pela <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> com amor comunitário.'
  [pt.params.facodi]
    languageLabel = "Português"
  [pt.params.doks]
    navBarButtonText = "Explorar trilhas"

[en]
  languageName = "English"
  weight = 2
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> with community pride.'
  [en.params.facodi]
    languageLabel = "English"
  [en.params.doks]
    navBarButtonText = "Explore tracks"
