[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = "Desenvolvido com <a class=\"text-muted\" href=\"https://facodi.pt/\">FACODI</a>"
    [pt.params.facodi]
      languageLabel = "Português"

[en]
  languageName = "English"
  contentDir = "content"
  weight = 2
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = "Powered by <a class=\"text-muted\" href=\"https://facodi.pt/\">FACODI</a>"
    [en.params.facodi]
      languageLabel = "English"

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 3
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = "Propulsé par <a class=\"text-muted\" href=\"https://facodi.pt/\">FACODI</a>"
    [fr.params.facodi]
      languageLabel = "Français"

[es]
  languageName = "Español"
  contentDir = "content"
  weight = 4
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
    footer = "Impulsado por <a class=\"text-muted\" href=\"https://facodi.pt/\">FACODI</a>"
    [es.params.facodi]
      languageLabel = "Español"
