[pt]
  languageName = "Português"
  weight = 10
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-BR"
    footer = 'Construído pela <a class="text-muted" href="https://monynha.com/" target="_blank" rel="noopener">Monynha Softwares</a> e pela comunidade FACODI.'
    alertText = '<strong>FACODI:</strong> educação superior aberta, gratuita e comunitária.'

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 20
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Built by <a class="text-muted" href="https://monynha.com/" target="_blank" rel="noopener">Monynha Softwares</a> with the FACODI community.'
    alertText = '<strong>FACODI:</strong> open, free and community-powered higher education.'
