[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Uma iniciativa da <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a>'

[en]
  languageName = "English"
  contentDir = "content"
  weight = 2
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a>'

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 3
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = 'Proposé par <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a>'

[es]
  languageName = "Español"
  contentDir = "content"
  weight = 4
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
    footer = 'Desarrollado por <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a>'
