[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 10
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"

[en]
  languageName = "Inglês"
  contentDir = "content"
  weight = 20
  [en.params]
    languageISO = "PT"
    languageTag = "pt-PT"

[fr]
  languageName = "Francês"
  contentDir = "content"
  weight = 30
  [fr.params]
    languageISO = "PT"
    languageTag = "pt-PT"

[es]
  languageName = "Espanhol"
  contentDir = "content"
  weight = 40
  [es.params]
    languageISO = "PT"
    languageTag = "pt-PT"
