[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 1
  languageCode = "pt-PT"
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"

[en]
  languageName = "English"
  contentDir = "content"
  weight = 2
  languageCode = "en-US"
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 3
  languageCode = "fr-FR"
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"

[es]
  languageName = "Español"
  contentDir = "content"
  weight = 4
  languageCode = "es-ES"
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
