[pt]
  languageName = "Português"
  weight = 1
  languageCode = "pt-PT"
  contentDir = "content"
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    [pt.params.facodi]
      languageLabel = "Português"

[en]
  languageName = "English"
  weight = 2
  languageCode = "en"
  contentDir = "content"
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    [en.params.facodi]
      languageLabel = "English"

[fr]
  languageName = "Français"
  weight = 3
  languageCode = "fr"
  contentDir = "content"
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    [fr.params.facodi]
      languageLabel = "Français"

[es]
  languageName = "Español"
  weight = 4
  languageCode = "es"
  contentDir = "content"
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
    [es.params.facodi]
      languageLabel = "Español"
