[pt]
  languageName = "Português"
  contentDir = "content"
  weight = 1
  [pt.params]
    languageISO = "PT"
    languageTag = "pt-PT"
    footer = 'Construído pela <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> com amor pela comunidade.'
    alertText = ''

[en]
  languageName = "English"
  contentDir = "content"
  weight = 5
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Built by <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> with love for the community.'
    alertText = ''

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 10
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = 'Réalisé par <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> avec amour pour la communauté.'
    alertText = ''

[es]
  languageName = "Español"
  contentDir = "content"
  weight = 15
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
    footer = 'Creado por <a class="text-muted" href="https://monynha.com/">Monynha Softwares</a> con cariño para la comunidad.'
    alertText = ''
