[[main]]
  identifier = "home"
  name = "Início"
  url = "/"
  weight = 1

[[main]]
  identifier = "courses"
  name = "Cursos"
  url = "/courses/"
  weight = 5

[[main]]
  identifier = "roadmap"
  name = "Roadmap"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  identifier = "privacy"
  name = "Política de Privacidade"
  url = "/privacy/"
  weight = 10
