[[main]]
  name = "Accueil"
  identifier = "home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cours"
  identifier = "courses"
  pageRef = "/courses/"
  weight = 5

[[main]]
  name = "Feuille de route"
  identifier = "roadmap"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  name = "Politique de confidentialit√©"
  identifier = "privacy"
  url = "/privacy/"
  weight = 10
