[[main]]
  name = "Início"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cursos"
  pageRef = "/courses"
  weight = 5

[[main]]
  name = "Manifesto"
  url = "https://monynha.com"
  weight = 10

[[footer]]
  name = "Política de privacidade"
  pageRef = "/privacy"
  weight = 10
