[[main]]
  name = "Início"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cursos"
  pageRef = "/courses"
  weight = 5

[[main]]
  name = "Manifesto"
  url = "https://monynha.com/manifesto"
  weight = 20

[[footer]]
  name = "Política de Privacidade"
  pageRef = "/legal/privacy"
  weight = 10
