[[main]]
  identifier = "home"
  name = "Accueil"
  url = "/"
  weight = 1

[[main]]
  identifier = "courses"
  name = "Parcours"
  url = "/courses/"
  weight = 5

[[main]]
  identifier = "roadmap"
  name = "Feuille de route"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  identifier = "privacy"
  name = "Politique de confidentialit√©"
  url = "/privacy/"
  weight = 10
