[[main]]
  name = "Inicio"
  identifier = "nav.menu.home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cursos"
  identifier = "nav.menu.courses"
  pageRef = "/courses/"
  weight = 5

[[main]]
  name = "Hoja de ruta"
  identifier = "nav.menu.roadmap"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  name = "Pol√≠tica de privacidad"
  identifier = "footer.menu.privacy"
  url = "/privacy/"
  weight = 10
