[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Courses"
  pageRef = "/courses"
  weight = 5

[[main]]
  name = "Community"
  url = "https://monynha.com"
  weight = 10

[[footer]]
  name = "Privacy policy"
  pageRef = "/privacy"
  weight = 10
