[[main]]
  name = "Home"
  identifier = "nav.menu.home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Courses"
  identifier = "nav.menu.courses"
  pageRef = "/courses/"
  weight = 5

[[main]]
  name = "Roadmap"
  identifier = "nav.menu.roadmap"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  identifier = "footer.menu.privacy"
  url = "/privacy/"
  weight = 10
