[[main]]
  identifier = "home"
  name = "Inicio"
  url = "/"
  weight = 1

[[main]]
  identifier = "courses"
  name = "Cursos"
  url = "/courses/"
  weight = 5

[[main]]
  identifier = "roadmap"
  name = "Hoja de ruta"
  url = "https://facodi.pt/roadmap"
  weight = 10

[[footer]]
  identifier = "privacy"
  name = "Pol√≠tica de privacidad"
  url = "/privacy/"
  weight = 10
